# Generated by Django 4.0 on 2022-01-02 10:57

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[account.validators.MinAgeValidator(13)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='private',
            field=models.BooleanField(default=True),
        ),
    ]
