# Generated by Django 4.0 on 2022-01-04 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_postmedia_delete_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmedia',
            old_name='img',
            new_name='media',
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_media', to='post.post'),
        ),
    ]
